databases:
  - name: infinite_back
    databaseName: infinite_back
    user: temi
    plan: free

services:
  - type: web
    name: infinite_back
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: infinite_back
          property: connectionString
      - key: 5d2a2a556bc081600596c7a2263ebf3c
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
